name: Automated Testing

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  automatic_test:
    env:
      DATABASE_URL: mysql://root:root@localhost:3306/app

    services:
      mysql:
        image: mariadb:latest

    strategy:
      matrix:
        php-versions: [ '8.1' ]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - name: Install MySQL
        run: sudo systemctl start mysql.service

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Validate composer.json and composer.lock
        run: composer validate --strict -n

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run Migration
        run: |
          php bin/console doctrine:database:drop --if-exists --force --no-interaction
          php bin/console doctrine:database:create --if-not-exists --no-interaction
          php bin/console doctrine:migrations:migrate --no-interaction

      - name: Validate Schema
        run: php bin/console doctrine:schema:validate

      - name: Composer Require Checker
        run: composer crc

      - name: Composer Unused
        run: composer-unused

      - name: CS Check
        run: composer cs-check-all

      - name: Prepare cache
        run: composer prepare-test

      - name: PHPStan
        run: composer phpstan

      - name: PHPUnit
        run: composer phpunit
